update preview generation script

diff --git a/.github/workflows/generate_previews.yml b/.github/workflows/generate_previews.yml
--- a/.github/workflows/generate_previews.yml
+++ b/.github/workflows/generate_previews.yml
@@ -44,7 +44,37 @@ jobs:
       with:
         flakes-from-devshell: true
         script: |
-          silicon ./preview/sources/rust.rs --output ./preview/images/rust.png --language rust --theme ./preview/themes/Catppuccin\ Frappe.tmTheme --pad-horiz 0 --pad-vert 0 --background '#fff0' --font "Iosevkata=48" --no-window-controls --no-round-corner
+          echo "Generating preview images from source files..."
+          echo
+
+          for file in ./preview/sources/*; do
+            filename=$(basename "$file")
+            name="${filename%.*}"
+            output="./preview/images/${name}.png"
+
+            echo "🔹 Processing: $filename"
+            echo "   ⮕ Output:   ${output}"
+
+            silicon "$file" \
+              --output "$output" \
+              --theme "./preview/themes/Catppuccin Frappe.tmTheme" \
+              --pad-horiz 0 \
+              --pad-vert 0 \
+              --background '#fff0' \
+              --font "Iosevkata=48" \
+              --no-window-controls \
+              --no-round-corner
+
+            if [ $? -eq 0 ]; then
+              echo "   ✅ Success"
+            else
+              echo "   ❌ Failed to generate image for $filename"
+            fi
+
+            echo
+          done
+
+          echo "Done!"
 
     - name: Configure Git Credentials
       run: |
@@ -53,11 +83,11 @@ jobs:
 
     - name: Push Preview Images
       run: |
-        if git diff --quiet -- ./previews/rust.png; then
+        if git status --porcelain preview/images | grep -E '^\s*[M?]'; then
           echo "Preview image unchanged, skipping commit."
         else
           echo "Preview image changed, committing..."
-          git add previews/rust.png
+          git add preview/images
           git commit -m "Update font preview"
           git push
         fi
